# Generated by Django 4.2.9 on 2026-01-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='reason',
        ),
    ]
