# Generated by Django 4.2.9 on 2025-11-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Add Purchase', 'verbose_name_plural': 'Add Purchases'},
        ),
    ]
