# Generated by Django 4.2.9 on 2025-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.PositiveIntegerField(),
        ),
    ]
