# Generated by Django 4.2.9 on 2025-11-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='remarks',
        ),
    ]
