# Generated by Django 4.2.9 on 2025-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchase_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
