# Generated by Django 4.2.9 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchase_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='selling_price',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Minimum Selling Price'),
        ),
    ]
