# Generated by Django 4.2.9 on 2025-11-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sizes_covered',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sizes',
        ),
    ]
