# Generated by Django 4.2.9 on 2025-11-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_category_sizes_covered_remove_stock_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_image',
        ),
    ]
