# Generated by Django 4.2.9 on 2026-01-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
