# Generated by Django 4.2.9 on 2026-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_description_stock_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(default=0, editable=False, verbose_name='Minimum Selling Price'),
        ),
    ]
