# Generated by Django 4.2.9 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stock_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Minimum Selling Price'),
        ),
    ]
