# Generated by Django 4.2.9 on 2025-11-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('selling_price', models.FloatField()),
                ('total_amount', models.FloatField(editable=False)),
                ('gross_profit', models.FloatField(default=0, editable=False)),
                ('sold_on', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sold_on'],
            },
        ),
        migrations.CreateModel(
            name='PreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('selling_price', models.FloatField()),
                ('total_amount', models.FloatField(editable=False)),
                ('gross_profit', models.FloatField(default=0, editable=False)),
                ('sold_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pres_sales', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Pre Sale',
                'verbose_name_plural': 'Pre Sales',
                'ordering': ['-sold_on'],
            },
        ),
    ]
