# Generated by Django 4.2.9 on 2025-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_delete_presales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
