# Generated by Django 4.2.9 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
