# Generated by Django 4.2.9 on 2026-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.FloatField(editable=False),
        ),
    ]
